### ISSUE TITLE
File naming from files to webserver

### ISSUE THREAD

**Issue by voxxi94** [fill30/valorant-overlay#4]
Webserver looks for 'valorant-overlay-1.1-all.jar', but, the file name in top folder is 'overlay-backend-1.1-all.jar' which stops the webserver from starting.

Renamed 'overlay-backend-1.1-all.jar' to 'valorant-overlay-1.1-all.jar' and then it starts.

May still create pathing issues

**Comment by fill30** [comment]
fixed
