### ISSUE TITLE
After setting, overlay does not change

### ISSUE THREAD

**Issue by voxxi94** [fill30/valorant-overlay#5]
http://localhost:7000/graphics/ does not change on setting new overlay. 

![4f259c20e0561c434e0df8d900277dce](https://user-images.githubusercontent.com/61507281/80693966-bbaea300-8acb-11ea-85e7-e6ed15953222.png)

Includes all team and agent logos. Team 1 name changes, however, team 2 name is always stuck as 'University of Exeter'. All playner names stuck as 'Player1-LEFT' depending on player number and side.

**Comment by fill30** [comment]
fixed
